--Create U tables

DROP TABLE IF EXISTS CFIG1,
	CFIG2,
	CFIG1_CFIG2 CASCADE;


DROP TABLE IF EXISTS UVALUE2;


CREATE TABLE UVALUE2 AS
SELECT U1.U1,
	U2.U2
FROM
	(SELECT COUNT(DISTINCT PUBPUB.DBLP_KEY) AS U1
		FROM PUB_DATA_PUBLICATION PUBPUB
		JOIN PUB_DATA_PUBLICATION_AUTHORS PUBPUBAUT ON PUBPUB.ID = PUBPUBAUT.PUBLICATION_ID
		JOIN PUB_DATA_AUTHORAFFILIATION PUBAUTAFF ON PUBPUBAUT.AUTHORAFFILIATION_ID = PUBAUTAFF.ID
		JOIN PUB_DATA_AUTHOR PUBAUTH ON PUBAUTAFF.AUTHOR_ID = PUBAUTH.ID
		JOIN PUBLICATION PUB ON PUBPUB.DBLP_KEY = PUB.PUBKEY
		JOIN PUBLICATIONS2 PUB2 ON PUB2.PUBID = PUB.PUBID
		JOIN PUB_DATA_AFFILIATION PUBAFF ON PUBAUTAFF.AFFILIATION_ID = PUBAFF.ID
		JOIN PUB_DATA_COUNTRY CONT ON CONT.ID = PUBAFF.COUNTRY_ID
		JOIN AUTHORED AUTHOREDTABLE ON AUTHOREDTABLE.PUBID = PUB2.PUBID
		JOIN AUTHOR2 AUTTABLE ON AUTTABLE.ID = AUTHOREDTABLE.ID
		WHERE PUB2.VENUE = 'PODS'
			AND (cont.name = 'United Kingdom' or autTable.dom = 'uk')
			AND PUB2.YEAR BETWEEN 2001 AND 2011 ) AS U1
JOIN
	(SELECT COUNT(DISTINCT PUBPUB.DBLP_KEY) AS U2
		FROM PUB_DATA_PUBLICATION PUBPUB
		JOIN PUB_DATA_PUBLICATION_AUTHORS PUBPUBAUT ON PUBPUB.ID = PUBPUBAUT.PUBLICATION_ID
		JOIN PUB_DATA_AUTHORAFFILIATION PUBAUTAFF ON PUBPUBAUT.AUTHORAFFILIATION_ID = PUBAUTAFF.ID
		JOIN PUB_DATA_AUTHOR PUBAUTH ON PUBAUTAFF.AUTHOR_ID = PUBAUTH.ID
		JOIN PUBLICATION PUB ON PUBPUB.DBLP_KEY = PUB.PUBKEY
		JOIN PUBLICATIONS2 PUB2 ON PUB2.PUBID = PUB.PUBID
		JOIN PUB_DATA_AFFILIATION PUBAFF ON PUBAUTAFF.AFFILIATION_ID = PUBAFF.ID
		JOIN PUB_DATA_COUNTRY CONT ON CONT.ID = PUBAFF.COUNTRY_ID
		JOIN AUTHORED AUTHOREDTABLE ON AUTHOREDTABLE.PUBID = PUB2.PUBID
		JOIN AUTHOR2 AUTTABLE ON AUTTABLE.ID = AUTHOREDTABLE.ID
		WHERE PUB2.VENUE = 'SIGMOD'
			AND (cont.name = 'United Kingdom' or autTable.dom = 'uk')
			AND PUB2.YEAR BETWEEN 2001 AND 2011 ) AS U2 ON 1 = 1;


CREATE TABLE CFIG1 AS
SELECT COALESCE(AUTTABLE.NAME,

								'EMPTY') AS NAME,
	COALESCE(PUBAFF.NAME,

		'EMPTY') AS INST,
	COALESCE(PUBAFF.CITY,

		'EMPTY') AS CITY,
	COUNT(DISTINCT PUBPUB.DBLP_KEY)
FROM PUB_DATA_PUBLICATION PUBPUB,
	PUB_DATA_AUTHORAFFILIATION PUBAUTAFF,
	PUB_DATA_AUTHOR PUBAUTH,
	PUB_DATA_PUBLICATION_AUTHORS PUBPUBAUT,
	PUBLICATION PUB,
	PUBLICATIONS2 PUB2,
	PUB_DATA_AFFILIATION PUBAFF,
	PUB_DATA_COUNTRY CONT,
	AUTHORED AUTHOREDTABLE,
	AUTHOR2 AUTTABLE
WHERE PUBPUB.ID = PUBPUBAUT.PUBLICATION_ID
	AND PUBAUTAFF.ID = PUBPUBAUT.AUTHORAFFILIATION_ID
	AND PUBAUTAFF.AUTHOR_ID = PUBAUTH.ID
	AND PUBAUTAFF.AFFILIATION_ID = PUBAFF.ID
	AND PUBPUB.DBLP_KEY = PUB.PUBKEY
	AND PUB2.PUBID = PUB.PUBID
	AND PUB2.VENUE = 'PODS'
	AND CONT.ID = PUBAFF.COUNTRY_ID
	AND (cont.name = 'United Kingdom' or autTable.dom = 'uk')
	AND AUTHOREDTABLE.PUBID = PUB2.PUBID
	AND AUTTABLE.ID = AUTHOREDTABLE.ID
	AND PUB2.YEAR BETWEEN 2001 AND 2011
GROUP BY CUBE(PUBAFF.NAME,

										PUBAFF.CITY,
										AUTTABLE.NAME);


CREATE TABLE CFIG2 AS
SELECT COALESCE(AUTTABLE.NAME,

								'EMPTY') AS NAME,
	COALESCE(PUBAFF.NAME,

		'EMPTY') AS INST,
	COALESCE(PUBAFF.CITY,

		'EMPTY') AS CITY,
	COUNT(DISTINCT PUBPUB.DBLP_KEY)
FROM PUB_DATA_PUBLICATION PUBPUB,
	PUB_DATA_AUTHORAFFILIATION PUBAUTAFF,
	PUB_DATA_AUTHOR PUBAUTH,
	PUB_DATA_PUBLICATION_AUTHORS PUBPUBAUT,
	PUBLICATION PUB,
	PUBLICATIONS2 PUB2,
	PUB_DATA_AFFILIATION PUBAFF,
	PUB_DATA_COUNTRY CONT,
	AUTHORED AUTHOREDTABLE,
	AUTHOR2 AUTTABLE
WHERE PUBPUB.ID = PUBPUBAUT.PUBLICATION_ID
	AND PUBAUTAFF.ID = PUBPUBAUT.AUTHORAFFILIATION_ID
	AND PUBAUTAFF.AUTHOR_ID = PUBAUTH.ID
	AND PUBAUTAFF.AFFILIATION_ID = PUBAFF.ID
	AND PUBPUB.DBLP_KEY = PUB.PUBKEY
	AND PUB2.PUBID = PUB.PUBID
	AND PUB2.VENUE = 'SIGMOD'
	AND CONT.ID = PUBAFF.COUNTRY_ID
	AND (cont.name = 'United Kingdom' or autTable.dom = 'uk')
	AND AUTHOREDTABLE.PUBID = PUB2.PUBID
	AND AUTTABLE.ID = AUTHOREDTABLE.ID
	AND PUB2.YEAR BETWEEN 2001 AND 2011
GROUP BY CUBE(PUBAFF.NAME,

										PUBAFF.CITY,
										AUTTABLE.NAME);


CREATE TABLE CFIG1_CFIG2 AS
SELECT DISTINCT COALESCE(C1.NAME,

																	C2.NAME) AS NAME,
	COALESCE(C1.INST,

		C2.INST) AS INST,
	COALESCE(C1.CITY,

		C2.CITY) AS CITY,
	COALESCE(C1.COUNT,
		0) AS V1,
	COALESCE(C2.COUNT,
		0) AS V2
FROM CFIG1 C1
FULL OUTER JOIN CFIG2 C2 ON C1.NAME = C2.NAME
AND C1.INST = C2.INST
AND C1.CITY = C2.CITY;


DROP VIEW IF EXISTS RESULT_VIEW2;


CREATE VIEW RESULT_VIEW2 AS
SELECT R.INST,
	R.NAME,
	R.CITY,
	(((CT.U2::FLOAT - R.V2::FLOAT) / (CT.U1::FLOAT - R.V1::FLOAT))) AS UINT
FROM UVALUE2 CT,
	CFIG1_CFIG2 R
WHERE CT.U2 != R.V2
	AND CT.U1 != R.V1;
